apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iam-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-postgres
spec:
  selector:
    matchLabels:
      app: iam-postgres
  template:
    metadata:
      labels:
        app: iam-postgres
    spec:
      containers:
      - name: iam-postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: iam-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iam-secrets
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: iam-secrets
              key: dbname
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: iam-postgres-storage
      volumes:
      - name: iam-postgres-storage
        persistentVolumeClaim:
          claimName: iam-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: iam-postgres-service
spec:
  ports:
  - port: 5432
  selector:
    app: iam-postgres