apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-server
  template:
    metadata:
      labels:
        app: iam-server
    spec:
      containers:
      - name: iam-server
        image: crymall/iam-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MIDDEN_API_KEY
          valueFrom:
            secretKeyRef:
              name: midden-global-secrets
              key: midden_api_key
        - name: CANTEEN_API_URL
          value: "http://canteen-service:3000"
        - name: DB_HOST
          value: "iam-postgres-service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: iam-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iam-secrets
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: iam-secrets
              key: dbname
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: iam-secrets
              key: jwt_secret
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: iam-secrets
              key: email_user
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: iam-secrets
              key: email_pass
---
apiVersion: v1
kind: Service
metadata:
  name: iam-service
spec:
  ports:
  - port: 3000
  selector:
    app: iam-server